baseurl = "/"
title = "My blog"
theme = "novela"

[Params]
    mainSections = ["post"]
    intro = true
    github = "https://github.com/codenameakshay/"
    email = "akshaymaurya3006@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    enableEmoji = true

[Permalinks]
    post = "/:filename/"