baseurl = "/"
title = "CodeNameAkshay's Blog"
theme = "dream"
paginate = 6

[Author]
    name = "Akshay Maurya"
    profile = "/about/"

[Params]
    mainSections = ["post"]
    contentTypeName = "content/post"
    themeColor = "orange"
    showLanguageSelector = false
    showMenuItems = 2
    fullWidthTheme = false
    centerTheme = false
    intro = true
    headline = "CodeNameAkshay's Blog"
    description = "Welcome to my blog. I will try to update it regularly, so that you can checkout different apps, projects that I built and I will also try to upload some tutorials on how I made them. Hope you have a great day!"
    linkedin = "https://www.linkedin.com/in/akshay-maurya-b56664170/"
    facebook = "https://www.facebook.com/akshay.maurya.180"
    github = "https://github.com/codenameakshay/"
    email = "akshaymaurya3006@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    enableEmoji = true
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "https://www.github.com/codenameakshay"
    weight = 2

[[menu.main]]
    name = "Mail"
    url = "mailto:ak@codenameakshay.tech"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
