github: "https://github.com/codenameakshay/"
instagram: "https://www.instagram.com/codename_photographer/"
linkedin: "https://www.linkedin.com/in/akshay-maurya-b56664170/"
facebook: "https://www.facebook.com/akshay.maurya.180"
resume: "https://codenameakshay.tech/resume.pdf"